apiVersion: v1
kind: Pod
metadata:
  name: ab-test
  namespace: default
spec:
  containers:
    - name: ab
      image: jordi/ab
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]
  restartPolicy: Never
